name: Cron remove-duplicates

on:
  # Once a day, in the middle of the night in Paris
  schedule:
    - cron: '26 23 * * *'
  workflow_dispatch:

concurrency:
  group: dzr-crons
  cancel-in-progress: false

jobs:
  run:
    uses: ./.github/workflows/crons.yml
    with:
      cron: remove-duplicates
      action: remove-duplicates
      arguments: |
        {
          "access_token": "$MY_ACCESS_TOKEN",
          "playlistId": 183341731
        }
    secrets: inherit
